### PR TITLE
Added the Animations branch with the intended changes for the the Flutter animations workshop

### PR DESCRIPTION
**Pull request by Morthor**

### CODE REVIEW

**Comment by Morthor** [comment]
I've had to add a 3rd commit to correct some changes I had done on my side to file names. It shouldn't cause any issues.

**Comment by Vanethos** [comment]
@Morthor Should this me a PR or an isolated branch so that people can easily change from the vanilla app, animations and firebase?

**Comment by Morthor** [comment]
I would keep it as a separate branch as we discussed. It will still have more changes as I update the workshop code.

**Comment by Morthor** [comment]
I now see the problem Vanethos, the PR was pointing to Master.

**Pull request closed without merging**
